/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class StdMapStringToMX extends java.util.AbstractMap<String, de.dhbw.rahmlab.casadi.impl.casadi.MX> {
  private final long swigCPtr;

  public StdMapStringToMX(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, StdMapStringToMX::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected StdMapStringToMX(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(StdMapStringToMX obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdMapStringToMX(swigCPtr);
}


  /**
  * Convenience constructor to use with Map.of().
  */
  public StdMapStringToMX(java.util.Map<? extends String, ? extends de.dhbw.rahmlab.casadi.impl.casadi.MX> other) {
    this();
    this.putAll(other);
  }

  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX put(String key, de.dhbw.rahmlab.casadi.impl.casadi.MX value) {
    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX itr = find(key);
    if (itr.isNot(end())) {
      de.dhbw.rahmlab.casadi.impl.casadi.MX oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX itr = find((String) key);
    if (itr.isNot(end())) {
      de.dhbw.rahmlab.casadi.impl.casadi.MX oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.MX>> entrySet() {
    java.util.Set<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.MX>> setToReturn =
        new java.util.HashSet<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.MX>>();

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX itr = begin();
    final de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.MX>() {
        private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX iterator;

        private Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.MX> init(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public de.dhbw.rahmlab.casadi.impl.casadi.MX getValue() {
          return iterator.getValue();
        }

        public de.dhbw.rahmlab.casadi.impl.casadi.MX setValue(de.dhbw.rahmlab.casadi.impl.casadi.MX newValue) {
          de.dhbw.rahmlab.casadi.impl.casadi.MX oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public StdMapStringToMX() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapStringToMX__SWIG_0(), true);
  }

  public StdMapStringToMX(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapStringToMX__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.getCPtr(other), other), true);
  }

  static public class StdMapIterStringToMX {
    private final long swigCPtr;
  
    public StdMapIterStringToMX(long cPtr, boolean cMemoryOwn) {
      this.swigCPtr = cPtr;
  	  if (cMemoryOwn) {
  		  REGISTER_DELETION(this, cPtr, StdMapIterStringToMX::delete);
    	}
    }
  
    /**
    * <pre>
    * In C++, deleting a pointer twice is undefined behavior!
    * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
    * Using this baseclass constructor for subtypes prevents that.
    * </pre>
    */
    protected StdMapIterStringToMX(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
      this.swigCPtr = cPtr;
  	  if (cMemoryOwn) {
  		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
  	  }
    }
  
    public static long getCPtr(StdMapIterStringToMX obj) {
      return obj.swigCPtr;
    }
  
    private static void delete(long swigCPtr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdMapStringToMX_StdMapIterStringToMX(swigCPtr);
  }
  
    private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX getNextUnchecked() {
      return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_StdMapIterStringToMX_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX other) {
      return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_StdMapIterStringToMX_isNot(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX.getCPtr(other), other);
    }
  
    private String getKey() {
      return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_StdMapIterStringToMX_getKey(swigCPtr, this);
    }
  
    private de.dhbw.rahmlab.casadi.impl.casadi.MX getValue() {
      return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_StdMapIterStringToMX_getValue(swigCPtr, this), true);
    }
  
    private void setValue(de.dhbw.rahmlab.casadi.impl.casadi.MX newValue) {
      de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_StdMapIterStringToMX_setValue(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(newValue), newValue);
    }
  
    public StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX other) {
      this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX.getCPtr(other), other), true);
    }
  
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_clear(swigCPtr, this);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX find(String key) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_find(swigCPtr, this, key), true);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX begin() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_begin(swigCPtr, this), true);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX end() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, de.dhbw.rahmlab.casadi.impl.casadi.MX value) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_putUnchecked(swigCPtr, this, key, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(value), value);
  }

  private void removeUnchecked(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX itr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToMX_removeUnchecked(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdMapStringToMX.StdMapIterStringToMX.getCPtr(itr), itr);
  }

}
