/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class StdMapStringToDM extends java.util.AbstractMap<String, de.dhbw.rahmlab.casadi.impl.casadi.DM> {
  private final long swigCPtr;

  public StdMapStringToDM(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, StdMapStringToDM::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected StdMapStringToDM(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(StdMapStringToDM obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdMapStringToDM(swigCPtr);
}


  /**
  * Convenience constructor to use with Map.of().
  */
  public StdMapStringToDM(java.util.Map<? extends String, ? extends de.dhbw.rahmlab.casadi.impl.casadi.DM> other) {
    this();
    this.putAll(other);
  }

  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM put(String key, de.dhbw.rahmlab.casadi.impl.casadi.DM value) {
    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM itr = find(key);
    if (itr.isNot(end())) {
      de.dhbw.rahmlab.casadi.impl.casadi.DM oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM itr = find((String) key);
    if (itr.isNot(end())) {
      de.dhbw.rahmlab.casadi.impl.casadi.DM oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.DM>> entrySet() {
    java.util.Set<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.DM>> setToReturn =
        new java.util.HashSet<Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.DM>>();

    de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM itr = begin();
    final de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.DM>() {
        private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM iterator;

        private Entry<String, de.dhbw.rahmlab.casadi.impl.casadi.DM> init(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public de.dhbw.rahmlab.casadi.impl.casadi.DM getValue() {
          return iterator.getValue();
        }

        public de.dhbw.rahmlab.casadi.impl.casadi.DM setValue(de.dhbw.rahmlab.casadi.impl.casadi.DM newValue) {
          de.dhbw.rahmlab.casadi.impl.casadi.DM oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public StdMapStringToDM() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapStringToDM__SWIG_0(), true);
  }

  public StdMapStringToDM(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapStringToDM__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.getCPtr(other), other), true);
  }

  static public class StdMapIterStringToDM {
    private final long swigCPtr;
  
    public StdMapIterStringToDM(long cPtr, boolean cMemoryOwn) {
      this.swigCPtr = cPtr;
  	  if (cMemoryOwn) {
  		  REGISTER_DELETION(this, cPtr, StdMapIterStringToDM::delete);
    	}
    }
  
    /**
    * <pre>
    * In C++, deleting a pointer twice is undefined behavior!
    * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
    * Using this baseclass constructor for subtypes prevents that.
    * </pre>
    */
    protected StdMapIterStringToDM(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
      this.swigCPtr = cPtr;
  	  if (cMemoryOwn) {
  		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
  	  }
    }
  
    public static long getCPtr(StdMapIterStringToDM obj) {
      return obj.swigCPtr;
    }
  
    private static void delete(long swigCPtr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdMapStringToDM_StdMapIterStringToDM(swigCPtr);
  }
  
    private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM getNextUnchecked() {
      return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_StdMapIterStringToDM_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM other) {
      return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_StdMapIterStringToDM_isNot(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM.getCPtr(other), other);
    }
  
    private String getKey() {
      return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_StdMapIterStringToDM_getKey(swigCPtr, this);
    }
  
    private de.dhbw.rahmlab.casadi.impl.casadi.DM getValue() {
      return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_StdMapIterStringToDM_getValue(swigCPtr, this), true);
    }
  
    private void setValue(de.dhbw.rahmlab.casadi.impl.casadi.DM newValue) {
      de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_StdMapIterStringToDM_setValue(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(newValue), newValue);
    }
  
    public StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM other) {
      this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM.getCPtr(other), other), true);
    }
  
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_clear(swigCPtr, this);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM find(String key) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_find(swigCPtr, this, key), true);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM begin() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_begin(swigCPtr, this), true);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM end() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, de.dhbw.rahmlab.casadi.impl.casadi.DM value) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_putUnchecked(swigCPtr, this, key, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(value), value);
  }

  private void removeUnchecked(de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM itr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdMapStringToDM_removeUnchecked(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdMapStringToDM.StdMapIterStringToDM.getCPtr(itr), itr);
  }

}
