/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class StdVectorVectorDouble extends java.util.AbstractList<de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorVectorDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorVectorDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdVectorVectorDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorVectorDouble(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble[] initialElements) {
    this();
    reserve(initialElements.length);

    for (de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble element : initialElements) {
      add(element);
    }
  }

  public StdVectorVectorDouble(Iterable<de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble> initialElements) {
    this();
    for (de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble element : initialElements) {
      add(element);
    }
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble get(int index) {
    return doGet(index);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble set(int index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble e) {
    return doSet(index, e);
  }

  public boolean add(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble e) {
    modCount++;
    doAdd(index, e);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public StdVectorVectorDouble() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorVectorDouble__SWIG_0(), true);
  }

  public StdVectorVectorDouble(de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorDouble other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorVectorDouble__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorDouble.getCPtr(other), other), true);
  }

  public long capacity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_clear(swigCPtr, this);
  }

  public StdVectorVectorDouble(int count, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble value) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorVectorDouble__SWIG_2(count, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(value), value), true);
  }

  private int doSize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doSize(swigCPtr, this);
  }

  private void doAdd(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doAdd__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(x), x);
  }

  private void doAdd(int index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doAdd__SWIG_1(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(x), x);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble doRemove(int index) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doRemove(swigCPtr, this, index), true);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble doGet(int index) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doGet(swigCPtr, this, index), false);
  }

  private de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble doSet(int index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble val) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doSet(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorVectorDouble_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
