/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class StdVectorCasadiSXElem extends java.util.AbstractList<de.dhbw.rahmlab.casadi.impl.casadi.SXElem> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorCasadiSXElem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorCasadiSXElem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdVectorCasadiSXElem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorCasadiSXElem(de.dhbw.rahmlab.casadi.impl.casadi.SXElem[] initialElements) {
    this();
    reserve(initialElements.length);

    for (de.dhbw.rahmlab.casadi.impl.casadi.SXElem element : initialElements) {
      add(element);
    }
  }

  public StdVectorCasadiSXElem(Iterable<de.dhbw.rahmlab.casadi.impl.casadi.SXElem> initialElements) {
    this();
    for (de.dhbw.rahmlab.casadi.impl.casadi.SXElem element : initialElements) {
      add(element);
    }
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.SXElem get(int index) {
    return doGet(index);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.SXElem set(int index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem e) {
    return doSet(index, e);
  }

  public boolean add(de.dhbw.rahmlab.casadi.impl.casadi.SXElem e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem e) {
    modCount++;
    doAdd(index, e);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.SXElem remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public StdVectorCasadiSXElem() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSXElem__SWIG_0(), true);
  }

  public StdVectorCasadiSXElem(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSXElem other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSXElem__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSXElem.getCPtr(other), other), true);
  }

  public long capacity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_clear(swigCPtr, this);
  }

  public StdVectorCasadiSXElem(int count, de.dhbw.rahmlab.casadi.impl.casadi.SXElem value) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSXElem__SWIG_2(count, de.dhbw.rahmlab.casadi.impl.casadi.SXElem.getCPtr(value), value), true);
  }

  private int doSize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doSize(swigCPtr, this);
  }

  private void doAdd(de.dhbw.rahmlab.casadi.impl.casadi.SXElem x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doAdd__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.SXElem.getCPtr(x), x);
  }

  private void doAdd(int index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doAdd__SWIG_1(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem.getCPtr(x), x);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.SXElem doRemove(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SXElem(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doRemove(swigCPtr, this, index), true);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.SXElem doGet(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SXElem(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doGet(swigCPtr, this, index), false);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.SXElem doSet(int index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem val) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SXElem(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doSet(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.SXElem.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSXElem_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
