/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class StdVectorCasadiSparsity extends java.util.AbstractList<de.dhbw.rahmlab.casadi.impl.casadi.Sparsity> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorCasadiSparsity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorCasadiSparsity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdVectorCasadiSparsity(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity[] initialElements) {
    this();
    reserve(initialElements.length);

    for (de.dhbw.rahmlab.casadi.impl.casadi.Sparsity element : initialElements) {
      add(element);
    }
  }

  public StdVectorCasadiSparsity(Iterable<de.dhbw.rahmlab.casadi.impl.casadi.Sparsity> initialElements) {
    this();
    for (de.dhbw.rahmlab.casadi.impl.casadi.Sparsity element : initialElements) {
      add(element);
    }
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity get(int index) {
    return doGet(index);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity set(int index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity e) {
    return doSet(index, e);
  }

  public boolean add(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity e) {
    modCount++;
    doAdd(index, e);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public StdVectorCasadiSparsity() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSparsity__SWIG_0(), true);
  }

  public StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSparsity__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(other), other), true);
  }

  public long capacity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_clear(swigCPtr, this);
  }

  public StdVectorCasadiSparsity(int count, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity value) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorCasadiSparsity__SWIG_2(count, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(value), value), true);
  }

  private int doSize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doSize(swigCPtr, this);
  }

  private void doAdd(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doAdd__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x);
  }

  private void doAdd(int index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doAdd__SWIG_1(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.Sparsity doRemove(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doRemove(swigCPtr, this, index), true);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.Sparsity doGet(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doGet(swigCPtr, this, index), false);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.Sparsity doSet(int index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity val) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doSet(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorCasadiSparsity_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
