/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class StdVectorDM extends java.util.AbstractList<de.dhbw.rahmlab.casadi.impl.casadi.DM> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorDM(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorDM obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdVectorDM(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorDM(de.dhbw.rahmlab.casadi.impl.casadi.DM[] initialElements) {
    this();
    reserve(initialElements.length);

    for (de.dhbw.rahmlab.casadi.impl.casadi.DM element : initialElements) {
      add(element);
    }
  }

  public StdVectorDM(Iterable<de.dhbw.rahmlab.casadi.impl.casadi.DM> initialElements) {
    this();
    for (de.dhbw.rahmlab.casadi.impl.casadi.DM element : initialElements) {
      add(element);
    }
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM get(int index) {
    return doGet(index);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM set(int index, de.dhbw.rahmlab.casadi.impl.casadi.DM e) {
    return doSet(index, e);
  }

  public boolean add(de.dhbw.rahmlab.casadi.impl.casadi.DM e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, de.dhbw.rahmlab.casadi.impl.casadi.DM e) {
    modCount++;
    doAdd(index, e);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.DM remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public StdVectorDM() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDM__SWIG_0(), true);
  }

  public StdVectorDM(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDM__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM.getCPtr(other), other), true);
  }

  public long capacity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_clear(swigCPtr, this);
  }

  public StdVectorDM(int count, de.dhbw.rahmlab.casadi.impl.casadi.DM value) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDM__SWIG_2(count, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(value), value), true);
  }

  private int doSize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doSize(swigCPtr, this);
  }

  private void doAdd(de.dhbw.rahmlab.casadi.impl.casadi.DM x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doAdd__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x);
  }

  private void doAdd(int index, de.dhbw.rahmlab.casadi.impl.casadi.DM x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doAdd__SWIG_1(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.DM doRemove(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doRemove(swigCPtr, this, index), true);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.DM doGet(int index) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doGet(swigCPtr, this, index), false);
  }

  private de.dhbw.rahmlab.casadi.impl.casadi.DM doSet(int index, de.dhbw.rahmlab.casadi.impl.casadi.DM val) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doSet(swigCPtr, this, index, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDM_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
