/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.std;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class StdVectorDouble extends java.util.AbstractList<Double> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_std_StdVectorDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorDouble(double[] initialElements) {
    this();
    reserve(initialElements.length);

    for (double element : initialElements) {
      add(element);
    }
  }

  public StdVectorDouble(Iterable<Double> initialElements) {
    this();
    for (double element : initialElements) {
      add(element);
    }
  }

  public Double get(int index) {
    return doGet(index);
  }

  public Double set(int index, Double e) {
    return doSet(index, e);
  }

  public boolean add(Double e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Double e) {
    modCount++;
    doAdd(index, e);
  }

  public Double remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public StdVectorDouble() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDouble__SWIG_0(), true);
  }

  public StdVectorDouble(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDouble__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(other), other), true);
  }

  public long capacity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_clear(swigCPtr, this);
  }

  public StdVectorDouble(int count, double value) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_std_StdVectorDouble__SWIG_2(count, value), true);
  }

  private int doSize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doSize(swigCPtr, this);
  }

  private void doAdd(double x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, double x) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private double doRemove(int index) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doRemove(swigCPtr, this, index);
  }

  private double doGet(int index) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doGet(swigCPtr, this, index);
  }

  private double doSet(int index, double val) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.std_StdVectorDouble_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
