/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class CodeGenerator {
  private final long swigCPtr;

  public CodeGenerator(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, CodeGenerator::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected CodeGenerator(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(CodeGenerator obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_CodeGenerator(swigCPtr);
}

  public CodeGenerator(String name, de.dhbw.rahmlab.casadi.impl.std.Dict opts) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_CodeGenerator__SWIG_0(name, de.dhbw.rahmlab.casadi.impl.std.Dict.getCPtr(opts), opts), true);
  }

  public CodeGenerator(String name) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_CodeGenerator__SWIG_1(name), true);
  }

  public void add(de.dhbw.rahmlab.casadi.impl.casadi.Function f, boolean with_jac_sparsity) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_add__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Function.getCPtr(f), f, with_jac_sparsity);
  }

  public void add(de.dhbw.rahmlab.casadi.impl.casadi.Function f) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_add__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Function.getCPtr(f), f);
  }

  public String dump() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_dump(swigCPtr, this);
  }

  public String generate(String prefix) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_generate__SWIG_0(swigCPtr, this, prefix);
  }

  public String generate() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_generate__SWIG_1(swigCPtr, this);
  }

  public void add_include(String new_include, boolean relative_path, String use_ifdef) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_add_include__SWIG_0(swigCPtr, this, new_include, relative_path, use_ifdef);
  }

  public void add_include(String new_include, boolean relative_path) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_add_include__SWIG_1(swigCPtr, this, new_include, relative_path);
  }

  public void add_include(String new_include) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_CodeGenerator_add_include__SWIG_2(swigCPtr, this, new_include);
  }

}
