/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  Sparsity interface class<br>
 * <br>
 *       This is a common base class for GenericMatrix (i.e. MX and Matrix&lt;&gt;) and Sparsity, introducing a<br>
 *       uniform syntax and implementing common functionality using the curiously recurring template pattern<br>
 *       (CRTP) idiom.<br>
 * <br>
 * <br>
 *       @author Joel Andersson<br>
 *       2014<br>
 * <br>
 *       
 */
public class DmSparsityInterface implements IDmSparsityInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DmSparsityInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DmSparsityInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_DmSparsityInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long IDmSparsityInterface_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_IDmSparsityInterface_GetInterfaceCPtr(swigCPtr);
  }

  /**
   *  Conditional comment: CLUTTER
   */
  public static SWIGTYPE_p_std__vectorT_std__vectorT_DM_t_t blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.DM x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt horz_offset) {
    return new SWIGTYPE_p_std__vectorT_std__vectorT_DM_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_blocksplit__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(vert_offset), vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(horz_offset), horz_offset), true);
  }

  public static SWIGTYPE_p_std__vectorT_std__vectorT_DM_t_t blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.DM x, long vert_incr, long horz_incr) {
    return new SWIGTYPE_p_std__vectorT_std__vectorT_DM_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_blocksplit__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x, vert_incr, horz_incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.DM veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.DM vec(de.dhbw.rahmlab.casadi.impl.casadi.DM x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_vec(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.DM repmat(de.dhbw.rahmlab.casadi.impl.casadi.DM x, long n, long m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_repmat__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x, n, m), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.DM repmat(de.dhbw.rahmlab.casadi.impl.casadi.DM x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_repmat__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM v, boolean vert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_offset__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM.getCPtr(v), v, vert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM v) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_offset__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorDM vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.DM x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.DM repmat(de.dhbw.rahmlab.casadi.impl.casadi.DM A, SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.DM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSparsityInterface_repmat__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(A), A, SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public DmSparsityInterface() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSparsityInterface__SWIG_0(), true);
  }

  public DmSparsityInterface(de.dhbw.rahmlab.casadi.impl.casadi.IDmSparsityInterface other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSparsityInterface__SWIG_1(other.IDmSparsityInterface_GetInterfaceCPtr(), other), true);
  }

}
