/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class DmSubIndex extends de.dhbw.rahmlab.casadi.impl.casadi.DM {
  private final long swigCPtr;

  public DmSubIndex(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubIndex_SWIGUpcast(cPtr), cMemoryOwn, cPtr, DmSubIndex::delete);
    this.swigCPtr = cPtr;
  }
  
  public static long getCPtr(DmSubIndex obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_DmSubIndex(swigCPtr);
}

  public DmSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.DM mat, int i) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSubIndex__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(mat), mat, i), true);
  }

  public DmSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.DmSubIndex y) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSubIndex__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.DmSubIndex.getCPtr(y), y), true);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.DmSubIndex other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubIndex_assign__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DmSubIndex.getCPtr(other), other);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.DM other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubIndex_assign__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(other), other);
  }

}
