/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  SubMatrix class for Matrix<br>
 *       SubMatrix is the return type for operator() of the Matrix class, it allows access to the value as well as changing the parent object<br>
 *       @author Joel Andersson<br>
 *       2011-2014
 */
public class DmSubMatrix extends de.dhbw.rahmlab.casadi.impl.casadi.DM {
  private transient long swigCPtr;

  public DmSubMatrix(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubMatrix_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(DmSubMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_DmSubMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Constructor
   */
  public DmSubMatrix(de.dhbw.rahmlab.casadi.impl.casadi.DM mat, int i, int j) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSubMatrix__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(mat), mat, i, j), true);
  }

  /**
   *  Default copy constructor
   */
  public DmSubMatrix(de.dhbw.rahmlab.casadi.impl.casadi.DmSubMatrix y) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_DmSubMatrix__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.DmSubMatrix.getCPtr(y), y), true);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.DmSubMatrix other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubMatrix_assign__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DmSubMatrix.getCPtr(other), other);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.DM other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_DmSubMatrix_assign__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(other), other);
  }

}
