/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class FileSerializer extends de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase {
  private transient long swigCPtr;

  public FileSerializer(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FileSerializer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(FileSerializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_FileSerializer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Advanced serialization of CasADi objects<br>
   * <br>
   * @see StringSerializer, FileDeserializer<br>
   * <br>
   *         
   */
  public FileSerializer(String fname, de.dhbw.rahmlab.casadi.impl.std.Dict opts) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_FileSerializer__SWIG_0(fname, de.dhbw.rahmlab.casadi.impl.std.Dict.getCPtr(opts), opts), true);
  }

  /**
   *  Advanced serialization of CasADi objects<br>
   * <br>
   * @see StringSerializer, FileDeserializer<br>
   * <br>
   *         
   */
  public FileSerializer(String fname) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_FileSerializer__SWIG_1(fname), true);
  }

}
