/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;

public class FileDeserializer extends de.dhbw.rahmlab.casadi.impl.casadi.DeserializerBase {
  private transient long swigCPtr;

  public FileDeserializer(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FileDeserializer_SWIGUpcast(cPtr), cMemoryOwn, cPtr, FileDeserializer::delete);
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(FileDeserializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (super.swigCMemOwn) {
        super.swigCMemOwn = false;
        FileDeserializer.delete(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() {
  }

  private static void delete(long swigCPtr) {
	synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_FileDeserializer(swigCPtr);
	}
}

  /**
   *  Advanced deserialization of CasADi objects<br>
   * <br>
   * @see FileSerializer<br>
   * <br>
   *          
   */
  public FileDeserializer(String fname) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_FileDeserializer(fname), true);
  }

}
