/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;
import de.dhbw.rahmlab.casadi.implUtil.CleanupPreventer;

/**
 *  Class to achieve minimal overhead function evaluations<br>
 * <br>
 *     
 */
public class FunctionBuffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;
  // Prevents double free after invoking delete().
  protected CleanupPreventer cleanupPreventer;

  public FunctionBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		this.cleanupPreventer = REGISTER_DELETION(this, this.swigCPtr, FunctionBuffer::delete);
	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected FunctionBuffer(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		this.cleanupPreventer = REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	}
  }

  public static long getCPtr(FunctionBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FunctionBuffer.delete(swigCPtr);
        this.cleanupPreventer.prevent();
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() throws Throwable {
	  super.finalize();
  }

  private static void delete(long swigCPtr) {
	// synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_FunctionBuffer(swigCPtr);
	// }
}

  /**
   *  Main constructor<br>
   * <br>
   *       
   */
  public FunctionBuffer(de.dhbw.rahmlab.casadi.impl.casadi.Function f) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_FunctionBuffer__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Function.getCPtr(f), f), true);
  }

  public FunctionBuffer(de.dhbw.rahmlab.casadi.impl.casadi.FunctionBuffer f) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_FunctionBuffer__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.FunctionBuffer.getCPtr(f), f), true);
  }

  /**
   *  Set input buffer for input i<br>
   * <br>
   *       mem.set_arg(0, memoryview(a))<br>
   * <br>
   *       Note that CasADi uses 'fortran' order: column-by-column<br>
   * <br>
   *       
   */
  public void set_arg(long i, SWIGTYPE_p_double a, long size) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FunctionBuffer_set_arg(swigCPtr, this, i, SWIGTYPE_p_double.getCPtr(a), size);
  }

  /**
   *  Set output buffer for ouput i<br>
   * <br>
   *       mem.set_res(0, memoryview(a))<br>
   * <br>
   *       Note that CasADi uses 'fortran' order: column-by-column<br>
   * <br>
   *       
   */
  public void set_res(long i, SWIGTYPE_p_double a, long size) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FunctionBuffer_set_res(swigCPtr, this, i, SWIGTYPE_p_double.getCPtr(a), size);
  }

  /**
   *  Get last return value
   */
  public int ret() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FunctionBuffer_ret(swigCPtr, this);
  }

  public void _eval() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_FunctionBuffer__eval(swigCPtr, this);
  }

  public SWIGTYPE_p_void _self() {throw new UnsupportedOperationException();}

}
