/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  Collects global CasADi options<br>
 * <br>
 * <br>
 * Note to developers:  <br>
 * <br>
 *  - use sparingly. Global options are - in general - a rather bad idea <br>
 * <br>
 *  - this class must never be instantiated. Access its static members directly <br>
 * <br>
 * <br>
 *  @author Joris Gillis<br>
 *  2012<br>
 * <br>
 *       
 */
public class GlobalOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public GlobalOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GlobalOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_GlobalOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void setSimplificationOnTheFly(boolean flag) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_setSimplificationOnTheFly(flag);
  }

  public static boolean getSimplificationOnTheFly() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_getSimplificationOnTheFly();
  }

  public static void setHierarchicalSparsity(boolean flag) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_setHierarchicalSparsity(flag);
  }

  public static boolean getHierarchicalSparsity() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_getHierarchicalSparsity();
  }

  public static void setCasadiPath(String path) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_setCasadiPath(path);
  }

  public static String getCasadiPath() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_getCasadiPath();
  }

  public static void setCasadiIncludePath(String path) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_setCasadiIncludePath(path);
  }

  public static String getCasadiIncludePath() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_getCasadiIncludePath();
  }

  public static void setMaxNumDir(long ndir) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_setMaxNumDir(ndir);
  }

  public static long getMaxNumDir() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_GlobalOptions_getMaxNumDir();
  }

  public GlobalOptions(de.dhbw.rahmlab.casadi.impl.casadi.GlobalOptions other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_GlobalOptions(de.dhbw.rahmlab.casadi.impl.casadi.GlobalOptions.getCPtr(other), other), true);
  }

}
