/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;

/**
 *  Sparsity interface class<br>
 * <br>
 *       This is a common base class for GenericMatrix (i.e. MX and Matrix&lt;&gt;) and Sparsity, introducing a<br>
 *       uniform syntax and implementing common functionality using the curiously recurring template pattern<br>
 *       (CRTP) idiom.<br>
 * <br>
 * <br>
 *       @author Joel Andersson<br>
 *       2014<br>
 * <br>
 *       
 */
public class ImSparsityInterface implements IImSparsityInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImSparsityInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, this.swigCPtr, ImSparsityInterface::delete);
	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected ImSparsityInterface(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	}
  }

  public static long getCPtr(ImSparsityInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ImSparsityInterface.delete(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() {
  }

  private static void delete(long swigCPtr) {
	synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_ImSparsityInterface(swigCPtr);
	}
}

  public long IImSparsityInterface_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_IImSparsityInterface_GetInterfaceCPtr(swigCPtr);
  }

  /**
   *  Conditional comment: CLUTTER
   */
  public static SWIGTYPE_p_std__vectorT_std__vectorT_casadi__MatrixT_casadi_int_t_t_t blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.IM x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt horz_offset) {
    return new SWIGTYPE_p_std__vectorT_std__vectorT_casadi__MatrixT_casadi_int_t_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_blocksplit__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(vert_offset), vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(horz_offset), horz_offset), true);
  }

  public static SWIGTYPE_p_std__vectorT_std__vectorT_casadi__MatrixT_casadi_int_t_t_t blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.IM x, long vert_incr, long horz_incr) {
    return new SWIGTYPE_p_std__vectorT_std__vectorT_casadi__MatrixT_casadi_int_t_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_blocksplit__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x, vert_incr, horz_incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.IM veccat(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.IM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_veccat(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t.getCPtr(x)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.IM vec(de.dhbw.rahmlab.casadi.impl.casadi.IM x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.IM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_vec(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.IM repmat(de.dhbw.rahmlab.casadi.impl.casadi.IM x, long n, long m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.IM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_repmat__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x, n, m), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.IM repmat(de.dhbw.rahmlab.casadi.impl.casadi.IM x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.IM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_repmat__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t v, boolean vert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_offset__SWIG_0(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t.getCPtr(v), vert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t v) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_offset__SWIG_1(SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t.getCPtr(v)), true);
  }

  public static SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.IM x, long n) {
    return new SWIGTYPE_p_std__vectorT_casadi__MatrixT_casadi_int_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.IM repmat(de.dhbw.rahmlab.casadi.impl.casadi.IM A, SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.IM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSparsityInterface_repmat__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(A), A, SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public ImSparsityInterface() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_ImSparsityInterface__SWIG_0(), true);
  }

  public ImSparsityInterface(de.dhbw.rahmlab.casadi.impl.casadi.IImSparsityInterface other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_ImSparsityInterface__SWIG_1(other.IImSparsityInterface_GetInterfaceCPtr(), other), true);
  }

}
