/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  SubIndex class for Matrix<br>
 *       Same as the above class but for single argument return for operator()<br>
 *       @author Joel Andersson<br>
 *       2011-2014
 */
public class ImSubIndex extends de.dhbw.rahmlab.casadi.impl.casadi.IM {
  private transient long swigCPtr;

  public ImSubIndex(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSubIndex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImSubIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_ImSubIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Constructor
   */
  public ImSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.IM mat, int i) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_ImSubIndex__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(mat), mat, i), true);
  }

  /**
   *  Default copy constructor
   */
  public ImSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.ImSubIndex y) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_ImSubIndex__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.ImSubIndex.getCPtr(y), y), true);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.ImSubIndex other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSubIndex_assign__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.ImSubIndex.getCPtr(other), other);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.IM other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_ImSubIndex_assign__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.IM.getCPtr(other), other);
  }

}
