/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class IndexAbstraction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IndexAbstraction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IndexAbstraction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_IndexAbstraction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexAbstraction() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_IndexAbstraction__SWIG_0(), true);
  }

  public long getStart() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_IndexAbstraction_start_get(swigCPtr, this);
  }

  public long getStop() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_IndexAbstraction_stop_get(swigCPtr, this);
  }

  public IndexAbstraction(de.dhbw.rahmlab.casadi.impl.casadi.IndexAbstraction other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_IndexAbstraction__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.IndexAbstraction.getCPtr(other), other), true);
  }

}
