/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class MetaVar extends de.dhbw.rahmlab.casadi.impl.casadi.IndexAbstraction {
  private transient long swigCPtr;

  public MetaVar(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MetaVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_MetaVar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getAttribute() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_attribute_get(swigCPtr, this);
  }

  public long getN() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_n_get(swigCPtr, this);
  }

  public long getM() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_m_get(swigCPtr, this);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.VariableType getType() {
    return de.dhbw.rahmlab.casadi.impl.casadi.VariableType.swigToEnum(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_type_get(swigCPtr, this));
  }

  public long getCount() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_count_get(swigCPtr, this);
  }

  public long getI() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_i_get(swigCPtr, this);
  }

  public long getActive_i() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_active_i_get(swigCPtr, this);
  }

  public de.dhbw.rahmlab.casadi.impl.std.Dict getExtra() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MetaVar_extra_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.Dict proxy = new de.dhbw.rahmlab.casadi.impl.std.Dict(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public MetaVar() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_MetaVar__SWIG_0(), true);
  }

  public MetaVar(de.dhbw.rahmlab.casadi.impl.casadi.MetaVar other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_MetaVar__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.MetaVar.getCPtr(other), other), true);
  }

}
