/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  SubIndex class for Matrix<br>
 *       Same as the above class but for single argument return for operator()<br>
 *       @author Joel Andersson<br>
 *       2011-2014
 */
public class MxSubIndex extends de.dhbw.rahmlab.casadi.impl.casadi.MX {
  private transient long swigCPtr;

  public MxSubIndex(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MxSubIndex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MxSubIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_MxSubIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Constructor
   */
  public MxSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.MX mat, int i) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_MxSubIndex__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(mat), mat, i), true);
  }

  /**
   *  Default copy constructor
   */
  public MxSubIndex(de.dhbw.rahmlab.casadi.impl.casadi.MxSubIndex y) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_MxSubIndex__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.MxSubIndex.getCPtr(y), y), true);
  }

  /**
   * Methods that modify a part of the parent object (A(i) = ?, A(i) += ?, etc.)
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.MX assign(de.dhbw.rahmlab.casadi.impl.casadi.MxSubIndex y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MxSubIndex_assign__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MxSubIndex.getCPtr(y), y), false);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX assign(de.dhbw.rahmlab.casadi.impl.casadi.MX y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_MxSubIndex_assign__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(y), y), false);
  }

}
