/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  A symbolic NLP representation<br>
 * <br>
 *   2012-2015<br>
 *   @author Joel Andersson<br>
 * <br>
 *       
 */
public class NlpBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public NlpBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(NlpBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_NlpBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Variables
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX getX() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_get(swigCPtr, this), false);
  }

  /**
   *  Objective
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.MX getF() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_f_get(swigCPtr, this), false);
  }

  /**
   *  Constraints
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX getG() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_get(swigCPtr, this), false);
  }

  /**
   *  Bounds on x
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_lb() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_lb_get(swigCPtr, this), false);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_ub() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_ub_get(swigCPtr, this), false);
  }

  /**
   *  Bounds on g
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getG_lb() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_lb_get(swigCPtr, this), false);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getG_ub() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_ub_get(swigCPtr, this), false);
  }

  /**
   *  Primal initial guess
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_init() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_init_get(swigCPtr, this), false);
  }

  /**
   *  Dual initial guess
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getLambda_init() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_lambda_init_get(swigCPtr, this), false);
  }

  /**
   *  Discrete variables
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorBool getDiscrete() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorBool(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_discrete_get(swigCPtr, this), false);
  }

  /**
   * Import an .nl file
   */
  public void import_nl(String filename, de.dhbw.rahmlab.casadi.impl.std.Dict opts) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_import_nl__SWIG_0(swigCPtr, this, filename, de.dhbw.rahmlab.casadi.impl.std.Dict.getCPtr(opts), opts);
  }

  /**
   * Import an .nl file
   */
  public void import_nl(String filename) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_import_nl__SWIG_1(swigCPtr, this, filename);
  }

  /**
   *  Readable name of the class
   */
  public String type_name() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_type_name(swigCPtr, this);
  }

  /**
   *  Print a description of the object
   */
  public void disp(SWIGTYPE_p_std__ostream stream, boolean more) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_disp__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream), more);
  }

  /**
   *  Print a description of the object
   */
  public void disp(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_disp__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  /**
   *  Get string representation
   */
  public String toString(boolean more) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_toString__SWIG_0(swigCPtr, this, more);
  }

  /**
   *  Get string representation
   */
  public String toString() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_toString__SWIG_1(swigCPtr, this);
  }

  public NlpBuilder() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_NlpBuilder__SWIG_0(), true);
  }

  public NlpBuilder(de.dhbw.rahmlab.casadi.impl.casadi.NlpBuilder other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_NlpBuilder__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.NlpBuilder.getCPtr(other), other), true);
  }

}
