/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class NlpBuilder {
  private final long swigCPtr;

  public NlpBuilder(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, NlpBuilder::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected NlpBuilder(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(NlpBuilder obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_NlpBuilder(swigCPtr);
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX getX() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorMX proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.casadi.MX getF() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_f_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.casadi.MX proxy = new de.dhbw.rahmlab.casadi.impl.casadi.MX(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX getG() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorMX proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_lb() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_lb_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_ub() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_ub_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getG_lb() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_lb_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getG_ub() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_g_ub_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getX_init() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_x_init_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble getLambda_init() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_lambda_init_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorBool getDiscrete() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_discrete_get(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	de.dhbw.rahmlab.casadi.impl.std.StdVectorBool proxy = new de.dhbw.rahmlab.casadi.impl.std.StdVectorBool(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public void import_nl(String filename, de.dhbw.rahmlab.casadi.impl.std.Dict opts) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_import_nl__SWIG_0(swigCPtr, this, filename, de.dhbw.rahmlab.casadi.impl.std.Dict.getCPtr(opts), opts);
  }

  public void import_nl(String filename) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_import_nl__SWIG_1(swigCPtr, this, filename);
  }

  public String type_name() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_type_name(swigCPtr, this);
  }

  public void disp(SWIGTYPE_p_std__ostream stream, boolean more) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_disp__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream), more);
  }

  public void disp(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_disp__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public String toString(boolean more) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_toString__SWIG_0(swigCPtr, this, more);
  }

  public String toString() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_NlpBuilder_toString__SWIG_1(swigCPtr, this);
  }

  public NlpBuilder() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_NlpBuilder__SWIG_0(), true);
  }

  public NlpBuilder(de.dhbw.rahmlab.casadi.impl.casadi.NlpBuilder other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_NlpBuilder__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.NlpBuilder.getCPtr(other), other), true);
  }

}
