/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;
import de.dhbw.rahmlab.casadi.implUtil.CleanupPreventer;

public class OptiAdvanced extends de.dhbw.rahmlab.casadi.impl.casadi.Opti {
  private transient long swigCPtr;

  public OptiAdvanced(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_SWIGUpcast(cPtr), cMemoryOwn, cPtr, OptiAdvanced::delete);
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(OptiAdvanced obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (super.swigCMemOwn) {
        super.swigCMemOwn = false;
        OptiAdvanced.delete(swigCPtr);
        super.cleanupPreventer.prevent();
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() throws Throwable {
	  super.finalize();
  }

  private static void delete(long swigCPtr) {
	// synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_OptiAdvanced(swigCPtr);
	// }
}

  public OptiAdvanced(de.dhbw.rahmlab.casadi.impl.casadi.Opti x) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_OptiAdvanced__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Opti.getCPtr(x), x), true);
  }

  /**
   *  Get the underlying CasADi solver of the Opti stack
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.Function casadi_solver() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Function(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_casadi_solver(swigCPtr, this), true);
  }

  /**
   *  return true if expression is only dependant on Opti parameters, not variables
   */
  public boolean is_parametric(de.dhbw.rahmlab.casadi.impl.casadi.MX expr) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_is_parametric(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(expr), expr);
  }

  /**
   *  Get symbols present in expression<br>
   * <br>
   *  Returned vector is ordered according to the order of<br>
   *  variable()/parameter() calls used to create the variables<br>
   * <br>
   *       
   */
  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX symvar() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_symvar__SWIG_0(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX symvar(de.dhbw.rahmlab.casadi.impl.casadi.MX expr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_symvar__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(expr), expr), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX symvar(de.dhbw.rahmlab.casadi.impl.casadi.MX expr, de.dhbw.rahmlab.casadi.impl.casadi.VariableType type) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_symvar__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(expr), expr, type.swigValue()), true);
  }

  /**
   *  Interpret an expression (for internal use only)
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.MetaCon canon_expr(de.dhbw.rahmlab.casadi.impl.casadi.MX expr) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MetaCon(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_canon_expr(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(expr), expr), true);
  }

  /**
   *  Get meta-data of symbol (for internal use only)
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.MetaVar get_meta(de.dhbw.rahmlab.casadi.impl.casadi.MX m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MetaVar(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_get_meta(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(m), m), true);
  }

  /**
   *  Get meta-data of symbol (for internal use only)
   */
  public de.dhbw.rahmlab.casadi.impl.casadi.MetaCon get_meta_con(de.dhbw.rahmlab.casadi.impl.casadi.MX m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MetaCon(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_get_meta_con(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(m), m), true);
  }

  /**
   *  Set meta-data of an expression
   */
  public void set_meta(de.dhbw.rahmlab.casadi.impl.casadi.MX m, de.dhbw.rahmlab.casadi.impl.casadi.MetaVar meta) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_set_meta(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(m), m, de.dhbw.rahmlab.casadi.impl.casadi.MetaVar.getCPtr(meta), meta);
  }

  /**
   *  Set meta-data of an expression
   */
  public void set_meta_con(de.dhbw.rahmlab.casadi.impl.casadi.MX m, de.dhbw.rahmlab.casadi.impl.casadi.MetaCon meta) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_set_meta_con(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(m), m, de.dhbw.rahmlab.casadi.impl.casadi.MetaCon.getCPtr(meta), meta);
  }

  public void assert_active_symbol(de.dhbw.rahmlab.casadi.impl.casadi.MX m) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_assert_active_symbol(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(m), m);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX active_symvar(de.dhbw.rahmlab.casadi.impl.casadi.VariableType type) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_active_symvar(swigCPtr, this, type.swigValue()), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorDM active_values(de.dhbw.rahmlab.casadi.impl.casadi.VariableType type) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorDM(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_active_values(swigCPtr, this, type.swigValue()), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX x_lookup(long i) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_x_lookup(swigCPtr, this, i), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX g_lookup(long i) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_g_lookup(swigCPtr, this, i), true);
  }

  public String x_describe(long i) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_x_describe(swigCPtr, this, i);
  }

  public String g_describe(long i) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_g_describe(swigCPtr, this, i);
  }

  public String describe(de.dhbw.rahmlab.casadi.impl.casadi.MX x, long indent) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_describe__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(x), x, indent);
  }

  public String describe(de.dhbw.rahmlab.casadi.impl.casadi.MX x) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_describe__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(x), x);
  }

  public void show_infeasibilities(double tol) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_show_infeasibilities__SWIG_0(swigCPtr, this, tol);
  }

  public void show_infeasibilities() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_show_infeasibilities__SWIG_1(swigCPtr, this);
  }

  public void solve_prepare() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solve_prepare(swigCPtr, this);
  }

  public SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t solve_actual(SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t args) {
    return new SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solve_actual(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t.getCPtr(args)), true);
  }

  public SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t arg() {
    return new SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_arg(swigCPtr, this), true);
  }

  public void res(SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t res) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_res__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t.getCPtr(res));
  }

  public SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t res() {
    return new SWIGTYPE_p_std__mapT_std__string_casadi__MatrixT_double_t_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_res__SWIG_1(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorMX constraints() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorMX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_constraints(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.MX objective() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.MX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_objective(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.OptiAdvanced baked_copy() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.OptiAdvanced(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_baked_copy(swigCPtr, this), true);
  }

  public void assert_empty() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_assert_empty(swigCPtr, this);
  }

  /**
   *  Fix the structure of the optimization problem
   */
  public void bake() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_bake(swigCPtr, this);
  }

  public boolean getProblem_dirty_() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_problem_dirty__get(swigCPtr, this);
  }

  public void mark_problem_dirty(boolean flag) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_problem_dirty__SWIG_0(swigCPtr, this, flag);
  }

  public void mark_problem_dirty() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_problem_dirty__SWIG_1(swigCPtr, this);
  }

  public boolean problem_dirty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_problem_dirty(swigCPtr, this);
  }

  public boolean getSolver_dirty_() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solver_dirty__get(swigCPtr, this);
  }

  public void mark_solver_dirty(boolean flag) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_solver_dirty__SWIG_0(swigCPtr, this, flag);
  }

  public void mark_solver_dirty() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_solver_dirty__SWIG_1(swigCPtr, this);
  }

  public boolean solver_dirty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solver_dirty(swigCPtr, this);
  }

  public boolean getSolved_() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solved__get(swigCPtr, this);
  }

  public void mark_solved(boolean flag) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_solved__SWIG_0(swigCPtr, this, flag);
  }

  public void mark_solved() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_mark_solved__SWIG_1(swigCPtr, this);
  }

  public boolean solved() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_solved(swigCPtr, this);
  }

  public void assert_solved() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_assert_solved(swigCPtr, this);
  }

  public void assert_baked() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_assert_baked(swigCPtr, this);
  }

  public long instance_number() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_OptiAdvanced_instance_number(swigCPtr, this);
  }

  public OptiAdvanced(de.dhbw.rahmlab.casadi.impl.casadi.OptiAdvanced other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_OptiAdvanced__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.OptiAdvanced.getCPtr(other), other), true);
  }

}
