/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class SerializerBase {
  private final long swigCPtr;

  public SerializerBase(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, SerializerBase::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected SerializerBase(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(SerializerBase obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SerializerBase(swigCPtr);
}

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.MX e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.MX.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.DM e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DM.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.SX e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_3(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.Linsol e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_4(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Linsol.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.Function e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_5(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Function.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.casadi.GenericType e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_6(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.GenericType.getCPtr(e), e);
  }

  public void pack(long e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_7(swigCPtr, this, e);
  }

  public void pack(double e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_8(swigCPtr, this, e);
  }

  public void pack(String e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_9(swigCPtr, this, e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_10(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorMX e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_11(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorMX.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorDM e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_12(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorDM.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_13(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorSX.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiLinsol e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_14(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiLinsol.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiFunction e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_15(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiFunction.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiGenericType e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_16(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiGenericType.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_17(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_18(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorDouble.getCPtr(e), e);
  }

  public void pack(de.dhbw.rahmlab.casadi.impl.std.StdVectorStdString e) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_pack__SWIG_19(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorStdString.getCPtr(e), e);
  }

  public static String type_to_string(de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType type) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_type_to_string(type.swigValue());
  }

  public void connect(de.dhbw.rahmlab.casadi.impl.casadi.DeserializerBase s) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_connect(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.DeserializerBase.getCPtr(s), s);
  }

  public void reset() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SerializerBase_reset(swigCPtr, this);
  }

  public final static class SerializationType {
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SPARSITY = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SPARSITY");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_MX_v1 = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_MX_v1");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_DM = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_DM");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SX_v1 = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SX_v1");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_LINSOL = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_LINSOL");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_FUNCTION = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_FUNCTION");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_GENERICTYPE = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_GENERICTYPE");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_INT = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_INT");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_DOUBLE = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_DOUBLE");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_STRING = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_STRING");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SPARSITY_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SPARSITY_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_MX_VECTOR_v1 = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_MX_VECTOR_v1");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_DM_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_DM_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SX_VECTOR_v1 = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SX_VECTOR_v1");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_LINSOL_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_LINSOL_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_FUNCTION_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_FUNCTION_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_GENERICTYPE_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_GENERICTYPE_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_INT_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_INT_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_DOUBLE_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_DOUBLE_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_STRING_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_STRING_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_MX = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_MX");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SX = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SX");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_MX_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_MX_VECTOR");
    public final static de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType SERIALIZED_SX_VECTOR = new de.dhbw.rahmlab.casadi.impl.casadi.SerializerBase.SerializationType("SERIALIZED_SX_VECTOR");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SerializationType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SerializationType.class + " with value " + swigValue);
    }

    private SerializationType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SerializationType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SerializationType(String swigName, SerializationType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SerializationType[] swigValues = { SERIALIZED_SPARSITY, SERIALIZED_MX_v1, SERIALIZED_DM, SERIALIZED_SX_v1, SERIALIZED_LINSOL, SERIALIZED_FUNCTION, SERIALIZED_GENERICTYPE, SERIALIZED_INT, SERIALIZED_DOUBLE, SERIALIZED_STRING, SERIALIZED_SPARSITY_VECTOR, SERIALIZED_MX_VECTOR_v1, SERIALIZED_DM_VECTOR, SERIALIZED_SX_VECTOR_v1, SERIALIZED_LINSOL_VECTOR, SERIALIZED_FUNCTION_VECTOR, SERIALIZED_GENERICTYPE_VECTOR, SERIALIZED_INT_VECTOR, SERIALIZED_DOUBLE_VECTOR, SERIALIZED_STRING_VECTOR, SERIALIZED_MX, SERIALIZED_SX, SERIALIZED_MX_VECTOR, SERIALIZED_SX_VECTOR };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
