/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class SparsityStruct {
  private final long swigCPtr;

  public SparsityStruct(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, SparsityStruct::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected SparsityStruct(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(SparsityStruct obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SparsityStruct(swigCPtr);
}

  public long getNrow() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_nrow_get(swigCPtr, this);
  }

  public long getNcol() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_ncol_get(swigCPtr, this);
  }

  public SWIGTYPE_p_long_long getColind() {throw new UnsupportedOperationException();}

  public SWIGTYPE_p_long_long getRow() {throw new UnsupportedOperationException();}

  public SparsityStruct() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsityStruct__SWIG_0(), true);
  }

  public SparsityStruct(de.dhbw.rahmlab.casadi.impl.casadi.SparsityStruct other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsityStruct__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SparsityStruct.getCPtr(other), other), true);
  }

}
