/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  Compact representation of a sparsity pattern<br>
 * <br>
 *         
 */
public class SparsityStruct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SparsityStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SparsityStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SparsityStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getNrow() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_nrow_get(swigCPtr, this);
  }

  public long getNcol() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_ncol_get(swigCPtr, this);
  }

  public SWIGTYPE_p_long_long getColind() {
    long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_colind_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public SWIGTYPE_p_long_long getRow() {
    long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsityStruct_row_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public SparsityStruct() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsityStruct__SWIG_0(), true);
  }

  public SparsityStruct(de.dhbw.rahmlab.casadi.impl.casadi.SparsityStruct other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsityStruct__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SparsityStruct.getCPtr(other), other), true);
  }

}
