/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;

public class Sparsity implements ISparsitySparsityInterface, ISharedObject {
  private final long swigCPtr;

  public Sparsity(long cPtr, boolean cMemoryOwn) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, cPtr, Sparsity::delete);
  	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected Sparsity(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    this.swigCPtr = cPtr;
	  if (cMemoryOwn) {
		  REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	  }
  }

  public static long getCPtr(Sparsity obj) {
    return obj.swigCPtr;
  }

  private static void delete(long swigCPtr) {
  de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_Sparsity(swigCPtr);
}

  public long ISparsitySparsityInterface_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_ISparsitySparsityInterface_GetInterfaceCPtr(swigCPtr);
  }

  public long ISharedObject_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_ISharedObject_GetInterfaceCPtr(swigCPtr);
  }

  public Sparsity(long dummy) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_0(dummy), true);
  }

  public Sparsity() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_1(), true);
  }

  public Sparsity(long nrow, long ncol) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_2(nrow, ncol), true);
  }

  public Sparsity(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row, boolean order_rows) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_3(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(colind), colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row, order_rows), true);
  }

  public Sparsity(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_4(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(colind), colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row), true);
  }

  public Sparsity(SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_5(SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public Sparsity(long nrow, long ncol, SWIGTYPE_p_long_long colind, SWIGTYPE_p_long_long row, boolean order_rows) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_6(nrow, ncol, SWIGTYPE_p_long_long.getCPtr(colind), SWIGTYPE_p_long_long.getCPtr(row), order_rows), true);
  }

  public Sparsity(long nrow, long ncol, SWIGTYPE_p_long_long colind, SWIGTYPE_p_long_long row) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_7(nrow, ncol, SWIGTYPE_p_long_long.getCPtr(colind), SWIGTYPE_p_long_long.getCPtr(row)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity create(SWIGTYPE_p_casadi__SparsityInternal node) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_create(SWIGTYPE_p_casadi__SparsityInternal.getCPtr(node)), true);
  }

  public SWIGTYPE_p_casadi__SparsityInternal get() {throw new UnsupportedOperationException();}

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity scalar(boolean dense_scalar) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_scalar__SWIG_0(dense_scalar), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity scalar() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_scalar__SWIG_1(), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity dense(long nrow, long ncol) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dense__SWIG_0(nrow, ncol), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity dense(long nrow) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dense__SWIG_1(nrow), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity dense(SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dense__SWIG_2(SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity unit(long n, long el) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_unit(n, el), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity upper(long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_upper(n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity lower(long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_lower(n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity diag(long nrow) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diag__SWIG_0(nrow), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity diag(long nrow, long ncol) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diag__SWIG_1(nrow, ncol), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity diag(SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diag__SWIG_2(SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity band(long n, long p) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_band(n, p), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity banded(long n, long p) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_banded(n, p), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity rowcol(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt col, long nrow, long ncol) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_rowcol(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(col), col, nrow, ncol), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity triplet(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt col, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT, boolean invert_mapping) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_triplet__SWIG_0(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(col), col, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT, invert_mapping), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity triplet(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt col) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_triplet__SWIG_1(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(col), col), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity nonzeros(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt nz, boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nonzeros__SWIG_0(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(nz), nz, ind1), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity nonzeros(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt nz) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nonzeros__SWIG_1(nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(nz), nz), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity compressed(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt v, boolean order_rows) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compressed__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(v), v, order_rows), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity compressed(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt v) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compressed__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity compressed(SWIGTYPE_p_long_long v, boolean order_rows) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compressed__SWIG_2(SWIGTYPE_p_long_long.getCPtr(v), order_rows), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity compressed(SWIGTYPE_p_long_long v) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compressed__SWIG_3(SWIGTYPE_p_long_long.getCPtr(v)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity permutation(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p, boolean invert) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_permutation__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p, invert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity permutation(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_permutation__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt permutation_vector(boolean invert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_permutation_vector__SWIG_0(swigCPtr, this, invert), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt permutation_vector() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_permutation_vector__SWIG_1(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity get_diag(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_diag(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt compress(boolean canonical) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compress__SWIG_0(swigCPtr, this, canonical), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt compress() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_compress__SWIG_1(swigCPtr, this), true);
  }

  public SWIGTYPE_p_casadi__SparsityInternal __ref__() {
	final long cPtr = de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity___ref__(swigCPtr, this);
	if (cPtr == 0) return null;
	// false here indicates no ownership transfer to java
	SWIGTYPE_p_casadi__SparsityInternal proxy = new SWIGTYPE_p_casadi__SparsityInternal(cPtr, false);
	// public void extend(final Object toBeExtendedLifeTime, final Object extendedToLifeTime)
	LIFE_TIME_EXTENDER.extend(this, proxy);
	return proxy;
}

  public boolean is_equal(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_equal__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y);
  }

  public boolean is_equal(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt row) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_equal__SWIG_1(swigCPtr, this, nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(colind), colind, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(row), row);
  }

  public boolean is_equal(long nrow, long ncol, SWIGTYPE_p_long_long colind, SWIGTYPE_p_long_long row) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_equal__SWIG_2(swigCPtr, this, nrow, ncol, SWIGTYPE_p_long_long.getCPtr(colind), SWIGTYPE_p_long_long.getCPtr(row));
  }

  public boolean is_stacked(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, long n) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_stacked(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, n);
  }

  public long size1() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_size1(swigCPtr, this);
  }

  public long rows() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_rows(swigCPtr, this);
  }

  public long size2() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_size2(swigCPtr, this);
  }

  public long columns() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_columns(swigCPtr, this);
  }

  public long numel() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_numel(swigCPtr, this);
  }

  public double density() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_density(swigCPtr, this);
  }

  public boolean is_empty(boolean both) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_empty__SWIG_0(swigCPtr, this, both);
  }

  public boolean is_empty() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_empty__SWIG_1(swigCPtr, this);
  }

  public long nnz() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz(swigCPtr, this);
  }

  public long nnz_upper(boolean strictly) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz_upper__SWIG_0(swigCPtr, this, strictly);
  }

  public long nnz_upper() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz_upper__SWIG_1(swigCPtr, this);
  }

  public long nnz_lower(boolean strictly) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz_lower__SWIG_0(swigCPtr, this, strictly);
  }

  public long nnz_lower() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz_lower__SWIG_1(swigCPtr, this);
  }

  public long nnz_diag() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_nnz_diag(swigCPtr, this);
  }

  public long bw_upper() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_bw_upper(swigCPtr, this);
  }

  public long bw_lower() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_bw_lower(swigCPtr, this);
  }

  public SWIGTYPE_p_std__pairT_long_long_long_long_t size() {
    return new SWIGTYPE_p_std__pairT_long_long_long_long_t(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_size__SWIG_0(swigCPtr, this), true);
  }

  public long size(long axis) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_size__SWIG_1(swigCPtr, this, axis);
  }

  public de.dhbw.rahmlab.casadi.impl.std.Dict info() {
    return new de.dhbw.rahmlab.casadi.impl.std.Dict(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_info(swigCPtr, this), true);
  }

  public void to_file(String filename, String format_hint) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_to_file__SWIG_0(swigCPtr, this, filename, format_hint);
  }

  public void to_file(String filename) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_to_file__SWIG_1(swigCPtr, this, filename);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity from_file(String filename, String format_hint) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_from_file__SWIG_0(filename, format_hint), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity from_file(String filename) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_from_file__SWIG_1(filename), true);
  }

  public void serialize(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_serialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public String serialize() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_serialize__SWIG_1(swigCPtr, this);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity deserialize(SWIGTYPE_p_std__istream stream) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_deserialize__SWIG_0(SWIGTYPE_p_std__istream.getCPtr(stream)), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity deserialize(String s) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_deserialize__SWIG_1(s), true);
  }

  public void serialize(SWIGTYPE_p_casadi__SerializingStream s) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_serialize__SWIG_2(swigCPtr, this, SWIGTYPE_p_casadi__SerializingStream.getCPtr(s));
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity deserialize(SWIGTYPE_p_casadi__DeserializingStream s) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_deserialize__SWIG_2(SWIGTYPE_p_casadi__DeserializingStream.getCPtr(s)), true);
  }

  public SWIGTYPE_p_long_long row() {throw new UnsupportedOperationException();}

  public SWIGTYPE_p_long_long colind() {throw new UnsupportedOperationException();}

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_row() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_row(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_colind() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_colind(swigCPtr, this), true);
  }

  public long colind(long cc) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_colind__SWIG_1(swigCPtr, this, cc);
  }

  public long row(long el) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_row__SWIG_1(swigCPtr, this, el);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_col() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_col(swigCPtr, this), true);
  }

  public void resize(long nrow, long ncol) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_resize(swigCPtr, this, nrow, ncol);
  }

  public long add_nz(long rr, long cc) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_add_nz(swigCPtr, this, rr, cc);
  }

  public long get_nz(long rr, long cc) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_nz__SWIG_0(swigCPtr, this, rr, cc);
  }

  public boolean has_nz(long rr, long cc) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_has_nz(swigCPtr, this, rr, cc);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_nz(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_nz__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc), true);
  }

  public void get_nz(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt INOUT) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_nz__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(INOUT), INOUT);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_lower() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_lower(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt get_upper() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_upper(swigCPtr, this), true);
  }

  public void get_ccs(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_ccs(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg1), arg1);
  }

  public void get_crs(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_crs(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg1), arg1);
  }

  public void get_triplet(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_get_triplet(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg1), arg1);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sub(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT, boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sub__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT, ind1), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sub(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sub__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sub(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT, boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sub__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT, ind1), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sub(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sub__SWIG_3(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity T() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_T(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity transpose(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT, boolean invert_mapping) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_transpose__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT, invert_mapping), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity transpose(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_transpose__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public boolean is_transpose(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_transpose(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y);
  }

  public boolean is_reshape(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_reshape(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity combine(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, boolean f0x_is_zero, boolean function0_is_zero, SWIGTYPE_p_std__vectorT_unsigned_char_t mapping) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_combine__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, f0x_is_zero, function0_is_zero, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(mapping)), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity combine(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, boolean f0x_is_zero, boolean function0_is_zero) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_combine__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, f0x_is_zero, function0_is_zero), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity unite(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, SWIGTYPE_p_std__vectorT_unsigned_char_t mapping) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_unite__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(mapping)), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity unite(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_unite__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity intersect(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, SWIGTYPE_p_std__vectorT_unsigned_char_t mapping) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_intersect__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(mapping)), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity intersect(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_intersect__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y), true);
  }

  public boolean is_subset(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity rhs) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_subset(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(rhs), rhs);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sparsity_cast_mod(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity X, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity Y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sparsity_cast_mod(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(X), X, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(Y), Y), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity pattern_inverse() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_pattern_inverse(swigCPtr, this), true);
  }

  public static void mul_sparsityF(SWIGTYPE_p_bvec_t x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x_sp, SWIGTYPE_p_bvec_t y, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y_sp, SWIGTYPE_p_bvec_t z, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity z_sp, SWIGTYPE_p_bvec_t w) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_mul_sparsityF(SWIGTYPE_p_bvec_t.getCPtr(x), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x_sp), x_sp, SWIGTYPE_p_bvec_t.getCPtr(y), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y_sp), y_sp, SWIGTYPE_p_bvec_t.getCPtr(z), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(z_sp), z_sp, SWIGTYPE_p_bvec_t.getCPtr(w));
  }

  public static void mul_sparsityR(SWIGTYPE_p_bvec_t x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x_sp, SWIGTYPE_p_bvec_t y, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y_sp, SWIGTYPE_p_bvec_t z, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity z_sp, SWIGTYPE_p_bvec_t w) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_mul_sparsityR(SWIGTYPE_p_bvec_t.getCPtr(x), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x_sp), x_sp, SWIGTYPE_p_bvec_t.getCPtr(y), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y_sp), y_sp, SWIGTYPE_p_bvec_t.getCPtr(z), de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(z_sp), z_sp, SWIGTYPE_p_bvec_t.getCPtr(w));
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity horzcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity sp) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_horzcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(sp), sp), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity vertcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity sp) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_vertcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(sp), sp), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity blockcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity v) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_blockcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity diagcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity v) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diagcat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity horzsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_horzsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(offset), offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity vertsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_vertsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(offset), offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity diagsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset2) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diagsplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(offset1), offset1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(offset2), offset2), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity mtimes(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_mtimes(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity mac(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity y, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity z) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_mac(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(y), y, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(z), z), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity reshape(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long nrow, long ncol) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_reshape__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, nrow, ncol), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity reshape(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_reshape__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sparsity_cast(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sparsity_cast(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp), true);
  }

  public static long sprank(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sprank(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x);
  }

  public static long norm_0_mul(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity A) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_norm_0_mul(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(A), A);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity kron(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity a, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity b) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_kron(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(a), a, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(b), b), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity triu(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, boolean includeDiagonal) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_triu__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, includeDiagonal), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity triu(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_triu__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity tril(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, boolean includeDiagonal) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_tril__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, includeDiagonal), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity tril(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_tril__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sum2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sum2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sum1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_sum1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public void enlarge(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc, boolean ind1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlarge__SWIG_0(swigCPtr, this, nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc, ind1);
  }

  public void enlarge(long nrow, long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlarge__SWIG_1(swigCPtr, this, nrow, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc);
  }

  public void enlargeRows(long nrow, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, boolean ind1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlargeRows__SWIG_0(swigCPtr, this, nrow, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, ind1);
  }

  public void enlargeRows(long nrow, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlargeRows__SWIG_1(swigCPtr, this, nrow, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr);
  }

  public void enlargeColumns(long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc, boolean ind1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlargeColumns__SWIG_0(swigCPtr, this, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc, ind1);
  }

  public void enlargeColumns(long ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_enlargeColumns__SWIG_1(swigCPtr, this, ncol, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity makeDense(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_makeDense(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt erase(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc, boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_erase__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc, ind1), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt erase(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt cc) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_erase__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(cc), cc), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt erase(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr, boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_erase__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr, ind1), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt erase(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt rr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_erase__SWIG_3(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(rr), rr), true);
  }

  public void append(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_append(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp);
  }

  public void appendColumns(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity sp) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_appendColumns(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(sp), sp);
  }

  public boolean is_scalar(boolean scalar_and_dense) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_scalar__SWIG_0(swigCPtr, this, scalar_and_dense);
  }

  public boolean is_scalar() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_scalar__SWIG_1(swigCPtr, this);
  }

  public boolean is_dense() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_dense(swigCPtr, this);
  }

  public boolean is_row() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_row(swigCPtr, this);
  }

  public boolean is_column() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_column(swigCPtr, this);
  }

  public boolean is_vector() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_vector(swigCPtr, this);
  }

  public boolean is_diag() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_diag(swigCPtr, this);
  }

  public boolean is_square() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_square(swigCPtr, this);
  }

  public boolean is_symmetric() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_symmetric(swigCPtr, this);
  }

  public boolean is_triu(boolean strictly) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_triu__SWIG_0(swigCPtr, this, strictly);
  }

  public boolean is_triu() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_triu__SWIG_1(swigCPtr, this);
  }

  public boolean is_tril(boolean strictly) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_tril__SWIG_0(swigCPtr, this, strictly);
  }

  public boolean is_tril() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_tril__SWIG_1(swigCPtr, this);
  }

  public boolean is_singular() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_singular(swigCPtr, this);
  }

  public boolean is_permutation() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_permutation(swigCPtr, this);
  }

  public boolean is_selection(boolean allow_empty) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_selection__SWIG_0(swigCPtr, this, allow_empty);
  }

  public boolean is_selection() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_selection__SWIG_1(swigCPtr, this);
  }

  public boolean is_orthonormal(boolean allow_empty) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal__SWIG_0(swigCPtr, this, allow_empty);
  }

  public boolean is_orthonormal() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal__SWIG_1(swigCPtr, this);
  }

  public boolean is_orthonormal_rows(boolean allow_empty) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal_rows__SWIG_0(swigCPtr, this, allow_empty);
  }

  public boolean is_orthonormal_rows() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal_rows__SWIG_1(swigCPtr, this);
  }

  public boolean is_orthonormal_columns(boolean allow_empty) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal_columns__SWIG_0(swigCPtr, this, allow_empty);
  }

  public boolean is_orthonormal_columns() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_is_orthonormal_columns__SWIG_1(swigCPtr, this);
  }

  public boolean rowsSequential(boolean strictly) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_rowsSequential__SWIG_0(swigCPtr, this, strictly);
  }

  public boolean rowsSequential() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_rowsSequential__SWIG_1(swigCPtr, this);
  }

  public void removeDuplicates(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt INOUT) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_removeDuplicates(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(INOUT), INOUT);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt etree(boolean ata) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_etree__SWIG_0(swigCPtr, this, ata), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt etree() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_etree__SWIG_1(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity ldl(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT, boolean amd) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_ldl__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT, amd), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity ldl(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt OUTPUT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_ldl__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(OUTPUT), OUTPUT), true);
  }

  public void qr_sparse(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity arg0, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg3, boolean amd) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_qr_sparse__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(arg1), arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg2), arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg3), arg3, amd);
  }

  public void qr_sparse(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity arg0, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg3) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_qr_sparse__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(arg1), arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg2), arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg3), arg3);
  }

  public long dfs(long j, long top, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg3, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt pinv, de.dhbw.rahmlab.casadi.impl.std.StdVectorBool arg5) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dfs(swigCPtr, this, j, top, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg2), arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg3), arg3, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(pinv), pinv, de.dhbw.rahmlab.casadi.impl.std.StdVectorBool.getCPtr(arg5), arg5);
  }

  public long scc(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg1) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_scc(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg1), arg1);
  }

  public long btf(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg3, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg4, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt arg5) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_btf(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg0), arg0, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg1), arg1, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg2), arg2, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg3), arg3, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg4), arg4, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(arg5), arg5);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt amd() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_amd(swigCPtr, this), true);
  }

  public void spsolve(SWIGTYPE_p_bvec_t X, SWIGTYPE_p_bvec_t B, boolean tr) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_spsolve(swigCPtr, this, SWIGTYPE_p_bvec_t.getCPtr(X), SWIGTYPE_p_bvec_t.getCPtr(B), tr);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt find(boolean ind1) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_find__SWIG_0(swigCPtr, this, ind1), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt find() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_find__SWIG_1(swigCPtr, this), true);
  }

  public void find(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt loc, boolean ind1) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_find__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(loc), loc, ind1);
  }

  public void find(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt loc) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_find__SWIG_3(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(loc), loc);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity uni_coloring(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity AT, long cutoff) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_uni_coloring__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(AT), AT, cutoff), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity uni_coloring(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity AT) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_uni_coloring__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(AT), AT), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity uni_coloring() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_uni_coloring__SWIG_2(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring(long ordering, long cutoff) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring__SWIG_0(swigCPtr, this, ordering, cutoff), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring(long ordering) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring__SWIG_1(swigCPtr, this, ordering), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring__SWIG_2(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring2(long ordering, long cutoff) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring2__SWIG_0(swigCPtr, this, ordering, cutoff), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring2(long ordering) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring2__SWIG_1(swigCPtr, this, ordering), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity star_coloring2() {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_star_coloring2__SWIG_2(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt largest_first() {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_largest_first(swigCPtr, this), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity pmult(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p, boolean permute_rows, boolean permute_columns, boolean invert_permutation) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_pmult__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p, permute_rows, permute_columns, invert_permutation), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity pmult(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p, boolean permute_rows, boolean permute_columns) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_pmult__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p, permute_rows, permute_columns), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity pmult(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p, boolean permute_rows) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_pmult__SWIG_2(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p, permute_rows), true);
  }

  public de.dhbw.rahmlab.casadi.impl.casadi.Sparsity pmult(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt p) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_pmult__SWIG_3(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(p), p), true);
  }

  public String dim(boolean with_nz) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dim__SWIG_0(swigCPtr, this, with_nz);
  }

  public String dim() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_dim__SWIG_1(swigCPtr, this);
  }

  public String postfix_dim() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_postfix_dim(swigCPtr, this);
  }

  public String repr_el(long k) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_repr_el(swigCPtr, this, k);
  }

  public void spy(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_spy__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public void spy() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_spy__SWIG_1(swigCPtr, this);
  }

  public void spy_matlab(String mfile) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_spy_matlab(swigCPtr, this, mfile);
  }

  public void export_code(String lang, SWIGTYPE_p_std__ostream stream, de.dhbw.rahmlab.casadi.impl.std.Dict options) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_export_code__SWIG_0(swigCPtr, this, lang, SWIGTYPE_p_std__ostream.getCPtr(stream), de.dhbw.rahmlab.casadi.impl.std.Dict.getCPtr(options), options);
  }

  public void export_code(String lang, SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_export_code__SWIG_1(swigCPtr, this, lang, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public void export_code(String lang) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_export_code__SWIG_2(swigCPtr, this, lang);
  }

  public static String type_name() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_type_name();
  }

  public long hash() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_hash(swigCPtr, this);
  }

  public static boolean test_cast(SWIGTYPE_p_SharedObjectInternal ptr) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_test_cast(SWIGTYPE_p_SharedObjectInternal.getCPtr(ptr));
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity kkt(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity J, boolean with_x_diag, boolean with_lam_g_diag) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_kkt__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(H), H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(J), J, with_x_diag, with_lam_g_diag), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity kkt(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity J, boolean with_x_diag) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_kkt__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(H), H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(J), J, with_x_diag), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity kkt(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity J) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_kkt__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(H), H, de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(J), J), true);
  }

  public static String file_format(String filename, String format_hint, SWIGTYPE_p_std__setT_std__string_t file_formats) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_file_format(filename, format_hint, SWIGTYPE_p_std__setT_std__string_t.getCPtr(file_formats));
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt horz_offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_blocksplit__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(vert_offset), vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(horz_offset), horz_offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long vert_incr, long horz_incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_blocksplit__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, vert_incr, horz_incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity vec(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_vec(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n, long m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_repmat__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n, m), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_repmat__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity v, boolean vert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_offset__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(v), v, vert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity v) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_offset__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity diagsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt output_offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diagsplit___SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(output_offset), output_offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity diagsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diagsplit___SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity diagsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long incr1, long incr2) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_diagsplit___SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, incr1, incr2), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity mtimes_(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity args) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_mtimes_(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(args), args), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity horzsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_horzsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity vertsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_vertsplit_(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity horzsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_horzsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity A, SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_repmat__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(A), A, SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public String toString(boolean more) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_toString__SWIG_0(swigCPtr, this, more);
  }

  public String toString() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_Sparsity_toString__SWIG_1(swigCPtr, this);
  }

  public Sparsity(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_Sparsity__SWIG_8(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(other), other), true);
  }

}
