/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

/**
 *  Sparsity interface class<br>
 * <br>
 *       This is a common base class for GenericMatrix (i.e. MX and Matrix&lt;&gt;) and Sparsity, introducing a<br>
 *       uniform syntax and implementing common functionality using the curiously recurring template pattern<br>
 *       (CRTP) idiom.<br>
 * <br>
 * <br>
 *       @author Joel Andersson<br>
 *       2014<br>
 * <br>
 *       
 */
public class SparsitySparsityInterface implements ISparsitySparsityInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SparsitySparsityInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SparsitySparsityInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SparsitySparsityInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long ISparsitySparsityInterface_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_ISparsitySparsityInterface_GetInterfaceCPtr(swigCPtr);
  }

  /**
   *  Conditional comment: CLUTTER
   */
  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt horz_offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_blocksplit__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(vert_offset), vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(horz_offset), horz_offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long vert_incr, long horz_incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_blocksplit__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, vert_incr, horz_incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity vec(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_vec(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n, long m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_repmat__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n, m), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_repmat__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity v, boolean vert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_offset__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(v), v, vert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity v) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_offset__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiSparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.Sparsity repmat(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity A, SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.Sparsity(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SparsitySparsityInterface_repmat__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.Sparsity.getCPtr(A), A, SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public SparsitySparsityInterface() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsitySparsityInterface__SWIG_0(), true);
  }

  public SparsitySparsityInterface(de.dhbw.rahmlab.casadi.impl.casadi.ISparsitySparsityInterface other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SparsitySparsityInterface__SWIG_1(other.ISparsitySparsityInterface_GetInterfaceCPtr(), other), true);
  }

}
