/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;

public class SXElem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SXElem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SXElem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SXElem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SXElem() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SXElem__SWIG_0(), true);
  }

  public SXElem(de.dhbw.rahmlab.casadi.impl.casadi.SXElem other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SXElem__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SXElem.getCPtr(other), other), true);
  }

}
