/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;

/**
 *  Sparsity interface class<br>
 * <br>
 *       This is a common base class for GenericMatrix (i.e. MX and Matrix&lt;&gt;) and Sparsity, introducing a<br>
 *       uniform syntax and implementing common functionality using the curiously recurring template pattern<br>
 *       (CRTP) idiom.<br>
 * <br>
 * <br>
 *       @author Joel Andersson<br>
 *       2014<br>
 * <br>
 *       
 */
public class SxSparsityInterface implements ISxSparsityInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SxSparsityInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, this.swigCPtr, SxSparsityInterface::delete);
	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected SxSparsityInterface(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	}
  }

  public static long getCPtr(SxSparsityInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SxSparsityInterface.delete(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() {
  }

  private static void delete(long swigCPtr) {
	synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SxSparsityInterface(swigCPtr);
	}
}

  public long ISxSparsityInterface_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_ISxSparsityInterface_GetInterfaceCPtr(swigCPtr);
  }

  /**
   *  Conditional comment: CLUTTER
   */
  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorSX blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.SX x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt horz_offset) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorSX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_blocksplit__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(vert_offset), vert_offset, de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt.getCPtr(horz_offset), horz_offset), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorSX blocksplit(de.dhbw.rahmlab.casadi.impl.casadi.SX x, long vert_incr, long horz_incr) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorVectorSX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_blocksplit__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x, vert_incr, horz_incr), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.SX veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_veccat(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.SX vec(de.dhbw.rahmlab.casadi.impl.casadi.SX x) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_vec(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.SX repmat(de.dhbw.rahmlab.casadi.impl.casadi.SX x, long n, long m) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_repmat__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x, n, m), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.SX repmat(de.dhbw.rahmlab.casadi.impl.casadi.SX x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_repmat__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX v, boolean vert) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_offset__SWIG_0(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX.getCPtr(v), v, vert), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt offset(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX v) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorCasadiInt(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_offset__SWIG_1(de.dhbw.rahmlab.casadi.impl.std.StdVectorSX.getCPtr(v), v), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.std.StdVectorSX vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.SX x, long n) {
    return new de.dhbw.rahmlab.casadi.impl.std.StdVectorSX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_vertsplit_n(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(x), x, n), true);
  }

  public static de.dhbw.rahmlab.casadi.impl.casadi.SX repmat(de.dhbw.rahmlab.casadi.impl.casadi.SX A, SWIGTYPE_p_std__pairT_long_long_long_long_t rc) {
    return new de.dhbw.rahmlab.casadi.impl.casadi.SX(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSparsityInterface_repmat__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(A), A, SWIGTYPE_p_std__pairT_long_long_long_long_t.getCPtr(rc)), true);
  }

  public SxSparsityInterface() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SxSparsityInterface__SWIG_0(), true);
  }

  public SxSparsityInterface(de.dhbw.rahmlab.casadi.impl.casadi.ISxSparsityInterface other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SxSparsityInterface__SWIG_1(other.ISxSparsityInterface_GetInterfaceCPtr(), other), true);
  }

}
