/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;
import static de.dhbw.rahmlab.casadi.implUtil.WrapUtil.*;
import de.dhbw.rahmlab.casadi.implUtil.CleanupPreventer;

/**
 *  SubMatrix class for Matrix<br>
 *       SubMatrix is the return type for operator() of the Matrix class, it allows access to the value as well as changing the parent object<br>
 *       @author Joel Andersson<br>
 *       2011-2014
 */
public class SxSubMatrix extends de.dhbw.rahmlab.casadi.impl.casadi.SX {
  private transient long swigCPtr;

  public SxSubMatrix(long cPtr, boolean cMemoryOwn) {
    super(de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSubMatrix_SWIGUpcast(cPtr), cMemoryOwn, cPtr, SxSubMatrix::delete);
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(SxSubMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (super.swigCMemOwn) {
        super.swigCMemOwn = false;
        SxSubMatrix.delete(swigCPtr);
        super.cleanupPreventer.prevent();
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() throws Throwable {
	  super.finalize();
  }

  private static void delete(long swigCPtr) {
	// synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_SxSubMatrix(swigCPtr);
	// }
}

  /**
   *  Constructor
   */
  public SxSubMatrix(de.dhbw.rahmlab.casadi.impl.casadi.SX mat, int i, int j) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SxSubMatrix__SWIG_0(de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(mat), mat, i, j), true);
  }

  /**
   *  Default copy constructor
   */
  public SxSubMatrix(de.dhbw.rahmlab.casadi.impl.casadi.SxSubMatrix y) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_SxSubMatrix__SWIG_1(de.dhbw.rahmlab.casadi.impl.casadi.SxSubMatrix.getCPtr(y), y), true);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.SxSubMatrix other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSubMatrix_assign__SWIG_0(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.SxSubMatrix.getCPtr(other), other);
  }

  public void assign(de.dhbw.rahmlab.casadi.impl.casadi.SX other) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_SxSubMatrix_assign__SWIG_1(swigCPtr, this, de.dhbw.rahmlab.casadi.impl.casadi.SX.getCPtr(other), other);
  }

}
