/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.casadi.impl.casadi;

import de.dhbw.rahmlab.casadi.impl.*;
import static de.dhbw.rahmlab.casadi.impl.core__.*;
import java.util.function.LongConsumer;

/**
 *  XML parser<br>
 * <br>
 *       Can be used for parsing XML files into CasADi data structures.<br>
 * <br>
 *       @author Joel Andersson<br>
 *       2014<br>
 * <br>
 *       
 */
public class XmlFile implements ISharedObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public XmlFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, this.swigCPtr, XmlFile::delete);
	}
  }

  /**
  * <pre>
  * In C++, deleting a pointer twice is undefined behavior!
  * In C++, deleting an object polymorphically is undefined behavior if the base class does not declare it's constructor as virtual!
  * Using this baseclass constructor for subtypes prevents that.
  * </pre>
  */
  protected XmlFile(long cPtr, boolean cMemoryOwn, long subtype_cPtr, LongConsumer subtype_deleteFunction) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
	if (cMemoryOwn) {
		REGISTER_DELETION(this, subtype_cPtr, subtype_deleteFunction);
	}
  }

  public static long getCPtr(XmlFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XmlFile.delete(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("deprecation")
  @Override
  protected void finalize() {
  }

  private static void delete(long swigCPtr) {
	synchronized (GLOBAL_DESTRUCTOR_LOCK) {
        de.dhbw.rahmlab.casadi.impl.core__JNI.delete_casadi_XmlFile(swigCPtr);
	}
}

  public long ISharedObject_GetInterfaceCPtr() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_ISharedObject_GetInterfaceCPtr(swigCPtr);
  }

  /**
   *  Get type name<br>
   * <br>
   *         
   */
  public static String type_name() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_type_name();
  }

  public XmlFile() {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_XmlFile__SWIG_0(), true);
  }

  public XmlFile(String name) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_XmlFile__SWIG_1(name), true);
  }

  /**
   *  Load a plugin dynamically
   */
  public static void load_plugin(String name) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_load_plugin(name);
  }

  /**
   *  Get solver specific documentation
   */
  public static String doc(String name) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_doc(name);
  }

  /**
   *  Get class name<br>
   * <br>
   *         
   */
  public String class_name() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_class_name(swigCPtr, this);
  }

  /**
   *  Print a description of the object
   */
  public void disp(SWIGTYPE_p_std__ostream stream, boolean more) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_disp__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream), more);
  }

  /**
   *  Print a description of the object
   */
  public void disp(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_disp__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  /**
   *  Get string representation
   */
  public String toString(boolean more) {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_toString__SWIG_0(swigCPtr, this, more);
  }

  /**
   *  Get string representation
   */
  public String toString() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_toString__SWIG_1(swigCPtr, this);
  }

  /**
   *  Conditional comment: INTERNAL Print the pointer to the internal class
   */
  public void print_ptr(SWIGTYPE_p_std__ostream stream) {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_print_ptr__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  /**
   *  Conditional comment: INTERNAL Print the pointer to the internal class
   */
  public void print_ptr() {
    de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_print_ptr__SWIG_1(swigCPtr, this);
  }

  /**
   *  End of conditional comment.Is a null pointer?
   */
  public boolean is_null() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile_is_null(swigCPtr, this);
  }

  /**
   *  Returns a number that is unique for a given Node.<br>
   * <br>
   * If the Object does not point to any node, "0" is returned.<br>
   * <br>
   *         
   */
  public long __hash__() {
    return de.dhbw.rahmlab.casadi.impl.core__JNI.casadi_XmlFile___hash__(swigCPtr, this);
  }

  public XmlFile(de.dhbw.rahmlab.casadi.impl.casadi.XmlFile other) {
    this(de.dhbw.rahmlab.casadi.impl.core__JNI.new_casadi_XmlFile__SWIG_2(de.dhbw.rahmlab.casadi.impl.casadi.XmlFile.getCPtr(other), other), true);
  }

}
